In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp
import pandas as pd
import sys
import platform
import sklearn
import statsmodels.api as sm

print(sys.version_info)
print("Python Version: " + str(platform.python_version()))

sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
Python Version: 3.6.8

In [10]:
from sklearn.feature_selection import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [35]:
#path = "/Users/zhiwei/Documents/Spring-2019/STAT-222/sf-crime/"
crime_data = pd.read_csv("../../data/data_include_all_features.csv")
crime_data = crime_data[crime_data.year<2017]
crime_data.shape

(1562, 176)

In [36]:
crime_data.columns.values

array(['GEOID', 'year', 'quarter', 'N', 'N_calls_311', 'lat', 'lng',
       'N_housing', 'V1', 'Estimate_Total.x', 'prop_rented', 'prop_male',
       'prop_african_american', 'prop_under_poverty_level',
       'prop_vacant_houses', 'prop_stable', 'racial_index',
       'income_index', 'age_index', 'working_class', 'land', 'water',
       'Estimate_Total.y', 'Female', 'Female_10_to_14_years',
       'Female_10th_grade', 'Female_11th_grade',
       'Female_12th_grade_no_diploma', 'Female_15_to_17_years',
       'Female_18_and_19_years', 'Female_20_years', 'Female_21_years',
       'Female_22_to_24_years', 'Female_25_to_29_years',
       'Female_30_to_34_years', 'Female_35_to_39_years',
       'Female_40_to_44_years', 'Female_45_to_49_years',
       'Female_5_to_9_years', 'Female_50_to_54_years',
       'Female_55_to_59_years', 'Female_5th_and_6th_grade',
       'Female_60_and_61_years', 'Female_62_to_64_years',
       'Female_65_and_66_years', 'Female_67_to_69_years',
       'Female_70_to_74_years', 'Female_75_to_79_years',
       'Female_7th_and_8th_grade', 'Female_80_to_84_years',
       'Female_85_years_and_over', 'Female_9th_grade',
       "Female_Associate's_degree", "Female_Bachelor's_degree",
       'Female_Doctorate_degree',
       'Female_High_school_graduate_(includes_equivalency)',
       "Female_Master's_degree", 'Female_No_schooling_completed',
       'Female_Nursery_to_4th_grade', 'Female_Professional_school_degree',
       'Female_Some_college_1_or_more_years_no_degree',
       'Female_Some_college_less_than_1_year', 'Female_Under_5_years',
       'Hispanic_or_Latino',
       'Hispanic_or_Latino_American_Indian_and_Alaska_Native_alone',
       'Hispanic_or_Latino_Asian_alone',
       'Hispanic_or_Latino_Black_or_African_American_alone',
       'Hispanic_or_Latino_Native_Hawaiian_and_Other_Pacific_Islander_alone',
       'Hispanic_or_Latino_Some_other_race_alone',
       'Hispanic_or_Latino_Two_or_more_races',
       'Hispanic_or_Latino_Two_or_more_races_Two_races_excluding_Some_other_race_and_three_or_more_races',
       'Hispanic_or_Latino_Two_or_more_races_Two_races_including_Some_other_race',
       'Hispanic_or_Latino_White_alone',
       'Income_in_the_past_12_months_at_or_above_poverty_level',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Female',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Female_In_labor_force',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Female_In_labor_force_Employed',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Female_In_labor_force_Unemployed',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Male',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Male_In_labor_force',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Male_In_labor_force_Employed',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Male_In_labor_force_Unemployed',
       'Income_in_the_past_12_months_at_or_above_poverty_level_Male_Not_in_labor_force',
       'Income_in_the_past_12_months_below_poverty_level',
       'Income_in_the_past_12_months_below_poverty_level_Female',
       'Income_in_the_past_12_months_below_poverty_level_Female_In_labor_force',
       'Income_in_the_past_12_months_below_poverty_level_Female_In_labor_force_Employed',
       'Income_in_the_past_12_months_below_poverty_level_Female_In_labor_force_Unemployed',
       'Income_in_the_past_12_months_below_poverty_level_Female_Not_in_labor_force',
       'Income_in_the_past_12_months_below_poverty_level_Male',
       'Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force',
       'Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force_Employed',
       'Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force_Unemployed',
       'Income_in_the_past_12_months_below_poverty_level_Male_Not_in_labor_force',
       'Male', 'Male_10_to_14_years', 'Male_10th_grade',
       'Male_11th_grade', 'Male_12th_grade_no_diploma',
       'Male_15_to_17_years', 'Male_18_and_19_years', 'Male_20_years',
       'Male_21_years', 'Male_22_to_24_years', 'Male_25_to_29_years',
       'Male_30_to_34_years', 'Male_35_to_39_years',
       'Male_40_to_44_years', 'Male_45_to_49_years', 'Male_5_to_9_years',
       'Male_50_to_54_years', 'Male_55_to_59_years',
       'Male_5th_and_6th_grade', 'Male_60_and_61_years',
       'Male_62_to_64_years', 'Male_65_and_66_years',
       'Male_67_to_69_years', 'Male_70_to_74_years',
       'Male_75_to_79_years', 'Male_7th_and_8th_grade',
       'Male_80_to_84_years', 'Male_85_years_and_over', 'Male_9th_grade',
       "Male_Associate's_degree", "Male_Bachelor's_degree",
       'Male_Doctorate_degree',
       'Male_High_school_graduate_(includes_equivalency)',
       "Male_Master's_degree", 'Male_No_schooling_completed',
       'Male_Nursery_to_4th_grade', 'Male_Professional_school_degree',
       'Male_Some_college_1_or_more_years_no_degree',
       'Male_Some_college_less_than_1_year', 'Male_Under_5_years',
       'Moved_from_abroad', 'Moved_from_abroad_Female',
       'Moved_from_abroad_Male',
       'Moved_from_different_county_within_same_state',
       'Moved_from_different_county_within_same_state_Female',
       'Moved_from_different_county_within_same_state_Male',
       'Moved_from_different_state', 'Moved_from_different_state_Female',
       'Moved_from_different_state_Male', 'Moved_within_same_county',
       'Moved_within_same_county_Female', 'Moved_within_same_county_Male',
       'Not_Hispanic_or_Latino',
       'Not_Hispanic_or_Latino_American_Indian_and_Alaska_Native_alone',
       'Not_Hispanic_or_Latino_Asian_alone',
       'Not_Hispanic_or_Latino_Black_or_African_American_alone',
       'Not_Hispanic_or_Latino_Native_Hawaiian_and_Other_Pacific_Islander_alone',
       'Not_Hispanic_or_Latino_Some_other_race_alone',
       'Not_Hispanic_or_Latino_Two_or_more_races',
       'Not_Hispanic_or_Latino_Two_or_more_races_Two_races_excluding_Some_other_race_and_three_or_more_races',
       'Not_Hispanic_or_Latino_Two_or_more_races_Two_races_including_Some_other_race',
       'Not_Hispanic_or_Latino_White_alone', 'Owner_occupied',
       'Renter_occupied', 'Same_house_1_year_ago',
       'Same_house_1_year_ago_Female', 'Same_house_1_year_ago_Male',
       'With_income', 'With_income_1_to_9999_or_loss',
       'With_income_10000_to_14999', 'With_income_15000_to_24999',
       'With_income_25000_to_34999', 'With_income_35000_to_49999',
       'With_income_50000_to_64999', 'With_income_65000_to_74999',
       'With_income_75000_or_more', 'N_theft', 'N_robbery', 'N_assualt',
       'N_vehicle_theft', 'N_burglary', 'NAME'], dtype=object)

# Select features according to the k highest scores

In [48]:
X = crime_data.iloc[:,4:170]
y = crime_data.N

#apply SelectKBest class to extract top 20 best features
bestfeatures = SelectKBest(score_func=f_regression, k=20)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(20,'Score'))  #print 20 best features

                                                 Specs        Score
89   Income_in_the_past_12_months_below_poverty_lev...  2341.283489
85   Income_in_the_past_12_months_below_poverty_lev...  1542.452875
0                                          N_calls_311  1470.594024
79    Income_in_the_past_12_months_below_poverty_level   915.512423
159                         With_income_10000_to_14999   864.855715
153                                    Renter_occupied   786.048537
141                      Moved_within_same_county_Male   674.957762
90                                                Male   636.501017
14                                           age_index   605.178816
22                                   Female_11th_grade   525.035923
135  Moved_from_different_county_within_same_state_...   519.434659
106                                Male_50_to_54_years   517.696430
139                           Moved_within_same_county   468.974796
103                                Male_40_to_44_years   468.327675
102                                Male_35_to_39_years   447.617499
138                    Moved_from_different_state_Male   429.078934
6                                          prop_rented   410.008444
136                         Moved_from_different_state   403.145834
157                                        With_income   401.953123
109                               Male_60_and_61_years   394.869532

array(['Income_in_the_past_12_months_below_poverty_level_Male',
       'Income_in_the_past_12_months_below_poverty_level_Female_In_labor_force',
       'GEOID'], dtype=object)

In [38]:
#Then use only number of thefts as y
X = crime_data.iloc[:,4:170][-np.isnan(crime_data.N_theft)]
y = crime_data.N_theft[-np.isnan(crime_data.N_theft)]

#apply SelectKBest class to extract top 20 best features
bestfeatures = SelectKBest(score_func=f_regression, k=20)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(20,'Score'))  #print 20 best features

                                                 Specs        Score
89   Income_in_the_past_12_months_below_poverty_lev...  1619.419726
0                                          N_calls_311  1175.872340
85   Income_in_the_past_12_months_below_poverty_lev...   898.982013
141                      Moved_within_same_county_Male   841.761179
135  Moved_from_different_county_within_same_state_...   815.803150
14                                           age_index   794.148685
153                                    Renter_occupied   735.577756
90                                                Male   696.643842
133      Moved_from_different_county_within_same_state   623.847363
139                           Moved_within_same_county   614.820240
103                                Male_40_to_44_years   595.238557
6                                          prop_rented   584.030056
136                         Moved_from_different_state   582.444623
102                                Male_35_to_39_years   568.240536
120                             Male_Bachelor's_degree   563.508584
79    Income_in_the_past_12_months_below_poverty_level   556.839161
106                                Male_50_to_54_years   546.818632
101                                Male_30_to_34_years   533.422843
165                          With_income_75000_or_more   509.063028
157                                        With_income   506.926921

In [39]:
#Number of robberies as y
X = crime_data.iloc[:,4:170][-np.isnan(crime_data.N_robbery)]
y = crime_data.N_robbery[-np.isnan(crime_data.N_robbery)]

#apply SelectKBest class to extract top 20 best features
bestfeatures = SelectKBest(score_func=f_regression, k=20)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(20,'Score'))  #print 20 best features

                                                 Specs        Score
89   Income_in_the_past_12_months_below_poverty_lev...  1840.415422
85   Income_in_the_past_12_months_below_poverty_lev...  1458.834980
159                         With_income_10000_to_14999   907.981625
79    Income_in_the_past_12_months_below_poverty_level   785.363755
0                                          N_calls_311   699.307168
22                                   Female_11th_grade   524.860506
153                                    Renter_occupied   477.222925
104                                Male_45_to_49_years   418.141331
122   Male_High_school_graduate_(includes_equivalency)   365.482859
93                                     Male_11th_grade   341.563618
90                                                Male   330.683160
106                                Male_50_to_54_years   326.118720
39                               Female_62_to_64_years   305.984915
109                               Male_60_and_61_years   291.440063
84   Income_in_the_past_12_months_below_poverty_lev...   283.022860
6                                          prop_rented   255.887194
141                      Moved_within_same_county_Male   255.795022
14                                           age_index   247.039983
119                            Male_Associate's_degree   219.798376
103                                Male_40_to_44_years   211.434025

In [15]:
#Number of assualts as y
# X = crime_data.iloc[:,4:170][-np.isnan(crime_data.N_assualt)]
# y = crime_data.N_assualt[-np.isnan(crime_data.N_assualt)]
crime_assualt = pd.read_csv("../../data/crime_assualt_data.csv")
crime_assualt = crime_assualt[crime_assualt.year<2017]

X = crime_assualt.iloc[:,6:183]
y = crime_assualt.crime

# standardizing features
X_scaler = StandardScaler()
X_scaler.fit(X)
X_scale = X_scaler.transform(X)
X_scale = pd.DataFrame(X_scale, columns=X.columns)

#apply SelectKBest class to extract top 20 best features
bestfeatures = SelectKBest(score_func=f_regression, k=20)
fit = bestfeatures.fit(X_scale,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X_scale.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(20,'Score'))  #print 20 best features
#print(X.columns.values[[70,66,60,140,161,103,67,122,134,65]])

                                                 Specs        Score
70   Income_in_the_past_12_months_below_poverty_lev...  3807.483306
66   Income_in_the_past_12_months_below_poverty_lev...  3664.761506
60    Income_in_the_past_12_months_below_poverty_level  2363.200815
140                         With_income_10000_to_14999  1894.075160
161                           prop_under_poverty_level  1325.716854
103   Male_High_school_graduate_(includes_equivalency)  1149.602393
67   Income_in_the_past_12_months_below_poverty_lev...  1024.132900
122                      Moved_within_same_county_Male   956.889149
134                                    Renter_occupied   932.412842
65   Income_in_the_past_12_months_below_poverty_lev...   927.661230
69   Income_in_the_past_12_months_below_poverty_lev...   926.446118
74                                     Male_11th_grade   908.227230
126  Not_Hispanic_or_Latino_Black_or_African_Americ...   781.124652
61   Income_in_the_past_12_months_below_poverty_lev...   756.739123
164                                       racial_index   718.769749
151                                         low_income   711.599592
108        Male_Some_college_1_or_more_years_no_degree   693.686417
3                                    Female_11th_grade   664.490842
172                                       school_SFCCD   656.828202
176                                        N_calls_311   623.020807

/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  del sys.path[0]

In [41]:
#Number of vehicle thefts as y
X = crime_data.iloc[:,4:170][-np.isnan(crime_data.N_vehicle_theft)]
y = crime_data.N_vehicle_theft[-np.isnan(crime_data.N_vehicle_theft)]

#apply SelectKBest class to extract top 20 best features
bestfeatures = SelectKBest(score_func=f_regression, k=20)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(20,'Score'))  #print 20 best features

                                                 Specs        Score
0                                          N_calls_311  1061.366849
103                                Male_40_to_44_years   492.560492
90                                                Male   486.411329
76   Income_in_the_past_12_months_at_or_above_pover...   427.497589
14                                           age_index   425.021969
75   Income_in_the_past_12_months_at_or_above_pover...   422.997936
74   Income_in_the_past_12_months_at_or_above_pover...   362.686278
102                                Male_35_to_39_years   358.318390
106                                Male_50_to_54_years   353.880428
157                                        With_income   352.008799
156                         Same_house_1_year_ago_Male   332.331611
2                                                  lng   330.134682
89   Income_in_the_past_12_months_below_poverty_lev...   304.439091
5                                     Estimate_Total.x   301.178879
18                                    Estimate_Total.y   301.178879
101                                Male_30_to_34_years   296.517540
30                               Female_30_to_34_years   278.899192
141                      Moved_within_same_county_Male   277.904141
120                             Male_Bachelor's_degree   275.576288
85   Income_in_the_past_12_months_below_poverty_lev...   273.950662

In [42]:
#Number of burglaries as y
X = crime_data.iloc[:,4:170][-np.isnan(crime_data.N_burglary)]
y = crime_data.N_burglary[-np.isnan(crime_data.N_burglary)]

#apply SelectKBest class to extract top 20 best features
bestfeatures = SelectKBest(score_func=f_regression, k=20)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(20,'Score'))  #print 20 best features

                                                 Specs        Score
89   Income_in_the_past_12_months_below_poverty_lev...  1092.997957
0                                          N_calls_311   956.343072
85   Income_in_the_past_12_months_below_poverty_lev...   694.455640
153                                    Renter_occupied   682.925516
141                      Moved_within_same_county_Male   670.520501
135  Moved_from_different_county_within_same_state_...   632.683357
14                                           age_index   629.843258
136                         Moved_from_different_state   552.193811
90                                                Male   513.964513
139                           Moved_within_same_county   513.086913
138                    Moved_from_different_state_Male   512.784028
101                                Male_30_to_34_years   478.315024
133      Moved_from_different_county_within_same_state   478.265161
6                                          prop_rented   474.697757
79    Income_in_the_past_12_months_below_poverty_level   473.158864
120                             Male_Bachelor's_degree   462.527179
102                                Male_35_to_39_years   453.099050
103                                Male_40_to_44_years   449.867595
165                          With_income_75000_or_more   422.589660
76   Income_in_the_past_12_months_at_or_above_pover...   389.729194

# Recursive Feature Elimination

In [43]:
#Recursive Feature Elimination
cols = list(X.columns)
model = LinearRegression()

#Initializing RFE model
rfe = RFE(model, 20)    

#Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

#Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

Index(['lat', 'lng', 'prop_rented', 'prop_male', 'prop_african_american',
       'prop_under_poverty_level', 'prop_stable', 'racial_index',
       'working_class', 'Female_11th_grade', 'Female_20_years',
       'Female_62_to_64_years', 'Hispanic_or_Latino_Asian_alone',
       'Male_10th_grade', 'Male_11th_grade', 'Male_12th_grade_no_diploma',
       'Male_60_and_61_years', 'Male_80_to_84_years',
       'Not_Hispanic_or_Latino_American_Indian_and_Alaska_Native_alone',
       'Not_Hispanic_or_Latino_Two_or_more_races_Two_races_including_Some_other_race'],
      dtype='object')

# Backward Elimination

In [44]:
#Backward Elimination
X = crime_data.iloc[:,4:170]
y = crime_data.N
cols = list(X.columns)
pmax = 1
while (len(cols)>0):
    p= []
    X_1 = X[cols]
    X_1 = sm.add_constant(X_1)
    model = sm.OLS(y,X_1).fit()
    p = pd.Series(model.pvalues.values[1:],index = cols)      
    pmax = max(p)
    feature_with_p_max = p.idxmax()
    if(pmax>0.01):
        cols.remove(feature_with_p_max)
    else:
        break
selected_features_BE = cols
print(selected_features_BE)

/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

['N_calls_311', 'lat', 'lng', 'V1', 'prop_rented', 'prop_african_american', 'prop_under_poverty_level', 'income_index', 'age_index', 'working_class', 'land', 'water', 'Female', 'Female_10th_grade', 'Female_11th_grade', 'Female_50_to_54_years', 'Female_60_and_61_years', 'Female_62_to_64_years', 'Female_70_to_74_years', 'Female_7th_and_8th_grade', 'Female_85_years_and_over', "Female_Master's_degree", 'Female_No_schooling_completed', 'Female_Under_5_years', 'Hispanic_or_Latino_American_Indian_and_Alaska_Native_alone', 'Hispanic_or_Latino_Two_or_more_races_Two_races_including_Some_other_race', 'Hispanic_or_Latino_White_alone', 'Income_in_the_past_12_months_at_or_above_poverty_level_Female', 'Income_in_the_past_12_months_at_or_above_poverty_level_Female_In_labor_force_Employed', 'Income_in_the_past_12_months_at_or_above_poverty_level_Male', 'Income_in_the_past_12_months_at_or_above_poverty_level_Male_In_labor_force', 'Income_in_the_past_12_months_at_or_above_poverty_level_Male_In_labor_force_Unemployed', 'Income_in_the_past_12_months_at_or_above_poverty_level_Male_Not_in_labor_force', 'Income_in_the_past_12_months_below_poverty_level_Female_In_labor_force_Employed', 'Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force', 'Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force_Employed', 'Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force_Unemployed', 'Male_10th_grade', 'Male_11th_grade', 'Male_12th_grade_no_diploma', 'Male_20_years', 'Male_22_to_24_years', 'Male_35_to_39_years', 'Male_50_to_54_years', 'Male_60_and_61_years', 'Male_75_to_79_years', 'Male_85_years_and_over', "Male_Associate's_degree", 'Male_High_school_graduate_(includes_equivalency)', 'Male_Nursery_to_4th_grade', 'Male_Professional_school_degree', 'Male_Some_college_1_or_more_years_no_degree', 'Moved_from_different_county_within_same_state_Male', 'Moved_from_different_state', 'Moved_within_same_county', 'Moved_within_same_county_Female', 'Not_Hispanic_or_Latino', 'Not_Hispanic_or_Latino_Black_or_African_American_alone', 'Not_Hispanic_or_Latino_Two_or_more_races', 'Not_Hispanic_or_Latino_Two_or_more_races_Two_races_excluding_Some_other_race_and_three_or_more_races', 'Not_Hispanic_or_Latino_Two_or_more_races_Two_races_including_Some_other_race', 'Owner_occupied', 'Same_house_1_year_ago_Female', 'With_income_10000_to_14999', 'With_income_65000_to_74999', 'With_income_75000_or_more']

In [45]:
model = sm.OLS(y,X[selected_features_BE]).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      N   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.949
Method:                 Least Squares   F-statistic:                     458.7
Date:                Mon, 06 May 2019   Prob (F-statistic):               0.00
Time:                        17:33:48   Log-Likelihood:                -9225.4
No. Observations:                1562   AIC:                         1.858e+04
Df Residuals:                    1499   BIC:                         1.891e+04
Df Model:                          63
Covariance Type:            nonrobust
========================================================================================================================================================================
                                                                                                           coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
N_calls_311                                                                                              0.1569      0.008     18.723      0.000       0.140       0.173
lat                                                                                                    837.9814    194.123      4.317      0.000     457.200    1218.763
lng                                                                                                    267.7464     59.683      4.486      0.000     150.676     384.817
V1                                                                                                      -0.0500      0.009     -5.326      0.000      -0.068      -0.032
prop_rented                                                                                           3010.2382    293.893     10.243      0.000    2433.753    3586.723
prop_african_american                                                                                 -573.2782     77.262     -7.420      0.000    -724.831    -421.725
prop_under_poverty_level                                                                               593.4016     87.631      6.772      0.000     421.510     765.293
income_index                                                                                            -0.2627      0.026    -10.030      0.000      -0.314      -0.211
age_index                                                                                               -0.0991      0.031     -3.215      0.001      -0.160      -0.039
working_class                                                                                          207.0429     56.168      3.686      0.000      96.866     317.220
land                                                                                                     0.0001   9.98e-06     10.233      0.000    8.26e-05       0.000
water                                                                                                -2.616e-05   5.05e-06     -5.183      0.000   -3.61e-05   -1.63e-05
Female                                                                                                  -0.4975      0.044    -11.323      0.000      -0.584      -0.411
Female_10th_grade                                                                                        0.5942      0.130      4.578      0.000       0.340       0.849
Female_11th_grade                                                                                        0.7403      0.141      5.269      0.000       0.465       1.016
Female_50_to_54_years                                                                                   -0.2014      0.051     -3.958      0.000      -0.301      -0.102
Female_60_and_61_years                                                                                   0.2729      0.082      3.318      0.001       0.112       0.434
Female_62_to_64_years                                                                                    0.3854      0.060      6.437      0.000       0.268       0.503
Female_70_to_74_years                                                                                   -0.5720      0.075     -7.668      0.000      -0.718      -0.426
Female_7th_and_8th_grade                                                                                -0.4152      0.090     -4.623      0.000      -0.591      -0.239
Female_85_years_and_over                                                                                -0.4101      0.068     -6.027      0.000      -0.544      -0.277
Female_Master's_degree                                                                                  -0.1358      0.036     -3.810      0.000      -0.206      -0.066
Female_No_schooling_completed                                                                           -0.2528      0.073     -3.481      0.001      -0.395      -0.110
Female_Under_5_years                                                                                     0.3107      0.058      5.336      0.000       0.197       0.425
Hispanic_or_Latino_American_Indian_and_Alaska_Native_alone                                               0.4212      0.116      3.630      0.000       0.194       0.649
Hispanic_or_Latino_Two_or_more_races_Two_races_including_Some_other_race                                -0.2980      0.081     -3.660      0.000      -0.458      -0.138
Hispanic_or_Latino_White_alone                                                                           0.1259      0.016      7.661      0.000       0.094       0.158
Income_in_the_past_12_months_at_or_above_poverty_level_Female                                            0.3284      0.038      8.571      0.000       0.253       0.404
Income_in_the_past_12_months_at_or_above_poverty_level_Female_In_labor_force_Employed                   -0.0895      0.029     -3.139      0.002      -0.145      -0.034
Income_in_the_past_12_months_at_or_above_poverty_level_Male                                             -0.1538      0.020     -7.660      0.000      -0.193      -0.114
Income_in_the_past_12_months_at_or_above_poverty_level_Male_In_labor_force                              -0.0789      0.016     -4.924      0.000      -0.110      -0.047
Income_in_the_past_12_months_at_or_above_poverty_level_Male_In_labor_force_Unemployed                   -0.3596      0.057     -6.312      0.000      -0.471      -0.248
Income_in_the_past_12_months_at_or_above_poverty_level_Male_Not_in_labor_force                          -0.0749      0.023     -3.323      0.001      -0.119      -0.031
Income_in_the_past_12_months_below_poverty_level_Female_In_labor_force_Employed                         -0.4455      0.062     -7.237      0.000      -0.566      -0.325
Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force                                    -0.2165      0.039     -5.555      0.000      -0.293      -0.140
Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force_Employed                           -0.4617      0.055     -8.422      0.000      -0.569      -0.354
Income_in_the_past_12_months_below_poverty_level_Male_In_labor_force_Unemployed                          0.2452      0.070      3.516      0.000       0.108       0.382
Male_10th_grade                                                                                         -0.4535      0.131     -3.451      0.001      -0.711      -0.196
Male_11th_grade                                                                                          0.5221      0.099      5.259      0.000       0.327       0.717
Male_12th_grade_no_diploma                                                                               0.6569      0.092      7.119      0.000       0.476       0.838
Male_20_years                                                                                            0.5692      0.100      5.717      0.000       0.374       0.765
Male_22_to_24_years                                                                                      0.2016      0.049      4.122      0.000       0.106       0.298
Male_35_to_39_years                                                                                      0.2190      0.035      6.257      0.000       0.150       0.288
Male_50_to_54_years                                                                                      0.2599      0.043      6.051      0.000       0.176       0.344
Male_60_and_61_years                                                                                     0.3869      0.075      5.161      0.000       0.240       0.534
Male_75_to_79_years                                                                                     -0.2566      0.086     -2.985      0.003      -0.425      -0.088
Male_85_years_and_over                                                                                  -0.4854      0.110     -4.404      0.000      -0.702      -0.269
Male_Associate's_degree                                                                                  0.3711      0.055      6.797      0.000       0.264       0.478
Male_High_school_graduate_(includes_equivalency)                                                         0.3859      0.030     12.661      0.000       0.326       0.446
Male_Nursery_to_4th_grade                                                                                0.7573      0.133      5.680      0.000       0.496       1.019
Male_Professional_school_degree                                                                          0.3330      0.052      6.383      0.000       0.231       0.435
Male_Some_college_1_or_more_years_no_degree                                                              0.3530      0.035     10.112      0.000       0.285       0.421
Moved_from_different_county_within_same_state_Male                                                       0.3291      0.046      7.176      0.000       0.239       0.419
Moved_from_different_state                                                                               0.2330      0.048      4.839      0.000       0.139       0.328
Moved_within_same_county                                                                                 0.2286      0.034      6.674      0.000       0.161       0.296
Moved_within_same_county_Female                                                                          0.2239      0.068      3.289      0.001       0.090       0.357
Not_Hispanic_or_Latino                                                                                   0.1832      0.016     11.187      0.000       0.151       0.215
Not_Hispanic_or_Latino_Black_or_African_American_alone                                                  -0.0379      0.009     -4.212      0.000      -0.056      -0.020
Not_Hispanic_or_Latino_Two_or_more_races                                                                -0.2277      0.072     -3.181      0.001      -0.368      -0.087
Not_Hispanic_or_Latino_Two_or_more_races_Two_races_excluding_Some_other_race_and_three_or_more_races     0.3204      0.074      4.304      0.000       0.174       0.466
Not_Hispanic_or_Latino_Two_or_more_races_Two_races_including_Some_other_race                            -0.5481      0.142     -3.870      0.000      -0.826      -0.270
Owner_occupied                                                                                          -0.0275      0.006     -4.731      0.000      -0.039      -0.016
Same_house_1_year_ago_Female                                                                             0.2860      0.040      7.103      0.000       0.207       0.365
With_income_10000_to_14999                                                                               0.3473      0.026     13.467      0.000       0.297       0.398
With_income_65000_to_74999                                                                              -0.1819      0.044     -4.157      0.000      -0.268      -0.096
With_income_75000_or_more                                                                                0.1513      0.017      8.909      0.000       0.118       0.185
==============================================================================
Omnibus:                      343.403   Durbin-Watson:                   0.806
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2658.600
Skew:                           0.807   Prob(JB):                         0.00
Kurtosis:                       9.184   Cond. No.                     1.29e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.32e-18. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""